### ISSUE TITLE
How to modify C++ code to calculate maximum value instead of minimum value？

### ISSUE THREAD

**Issue by HXMing** [hrldcpr/pyLAPJV#6]
I want to calculate the maximum value, but I don’t want to achieve it by taking a negative number on the matrix. How can I directly modify the code?

**Comment by hrldcpr** [comment]
I'm not sure, sorry. `lap.cpp` is the relevant file, and you could try swapping every `>` and `<` (and perhaps every `min` and `max` naming for clarity).

Negating the matrix is very fast though, so that seems like the best solution. I.e. `lap(-costs)` should work, I believe.
